---
- name: get telegraf
  get_url: url= dest=/tmp/telegraf_.deb  mode=0740 timeout=250
- name: install telegraf
  apt: deb=/tmp/telegraf_.deb
- name: allow docker access to telegraf
  user: name=telegraf
        shell=/bin/bash
        group=docker
        append=yes
- name: cleanup
  file: path=/tmp/telegraf_.deb state=absent
- name: Assures /etc/telegraf dir exists
  file: path=/etc/telegraf state=directory
- name: Provision Telegraf Config
  copy: src=telegraf.conf dest=/etc/telegraf/telegraf.conf owner=pirate mode="u=r,g=r,o=r"
  notify:
      - reload systemd
